Chinachu/Chinachu

chinachu
=> Fix shebang

web/chinachu.js
リバースプロキシ使用時、ルート以外のパスに設定しても、ルート直下(/socket.io)に接続される問題を修正しました。
#114 の対応だけでは動作しませんでした。
=> WUI/Client: リバースプロキシ使用時の不具合を修正

app-scheduler.js
アニメのタイトルが「TVアニメ」で始まる際に「TV」部分が残ってしまう件の修正です。
例：
修正前：TVアニメ「Fate/stay night」 → TVFate/stay night
修正後：TVアニメ「Fate/stay night」 → Fate/stay night
=> Improve regular expression for anime title

api/script-rules-rule.vm.js, api/script-rules.vm.js
`/api/rules.json`に空のPOSTを送ると空のオブジェクトがルールに追加されますが、このルールはCLIが削除することができません(削除するには一旦何か条件を追加する必要があります)。
これを回避するためにPOSTの内容が空の場合は400エラーを返すようにしました。
例えば以下のコードで空のルールを作成することができます。
```
curl http://192.168.x.y:zzzzz/api/rules.json -X POST -H 'content-type:application/json'
```
このルールがN番目に作成されたとすると、これを削除する以下のコードは500エラーとなります(`-w '%{http_code}\n'`を追加することによりステータスコードを確認できます)。
```
curl http://192.168.x.y:zzzzz/api/rules/N.json -X DELETE
```
以下のように一旦条件を追加することにより削除できます。
```
curl http://192.168.x.y:zzzzz/api/rules/N.json -X PUT -H 'content-type:application/json' -d '{"reserve_titles":["foo"]}'
curl http://192.168.x.y:zzzzz/api/rules/N.json -X DELETE
```
PUTでも同じようなことができました。
```
curl http://192.168.x.y:zzzzz/api/rules/N.json -X PUT -H 'content-type:application/json'
```
=> API: reject empty rule post and put

app-operator.js
config.json で operRecOffsetStart および operRecOffsetEnd に 0 を設定すると、規定値の 5000 と -8000 が設定されてしまうようです。
=> config.jsonでoperRecOffsetStart,operRecOffsetEndに0を設定できない問題を修正

app-wui.js
いつの日からか自環境・でもサーバー共に、log/wuiにAPIのアクセスログが記載されなくなってしまっていたのでnodejsのドキュメントを追ったところ、
http.responseのfinishイベント発火にてコネクション終了通知になっていたのでそのように修正しました。
従来のresponseのcloseイベントはレスポンスが返し終わる前に接続が終了された場合に発火するようなので、その部分は残し、
requestのcloseイベントは発火しないようなので消しました。
=> APIへアクセスしたログがlog/wuiに記載されない問題の修正

api/script-channel-watch.vm.js, app-operator.js, app-scheduler.js, chinachu, node_modules/chinachu-common/lib/chinachu-common.js
クライアントでライブ視聴をよくするので、ライブ視聴に関するチューナー優先度を導入しました。
ライブ視聴時に録画が始まった際にチューナーが足りずに録画できない問題を解消すべく、
| チューナー使用タイプ | 優先度 |
|:-------------------------------|:--------:|
|スケジューラー             |  低(0)  |
|ライブ視聴                    |  中(1)  |
|録画                               |  高(2)  |
として優先度順にチューナーを奪取できるようにしました。
ついでに使われていない処理を掃除しました。
=> チューナー使用優先度の導入

api/script-recorded-program-watch.vm.js
9cf3545aeebd4c53855056e7805390ed6e5eedde にて、d.ssの最小値が'2'に変更されているのにもかかわらず、Range付きリクエストの判定で'0'と比較していたのでその部分を修正。
=> Fix recorded programs streaming range

chinachu
WUIでスケジューラを実行したときに、裏でEPG取得が走っているとき、`chinachu update`では
ERROR: Scheduler is already running.
と出力するにも関わらず、リターンコード0で終了していました。
そのため、/api/scheduler.jsonにputしても200が返り、WUIに「スケジュール実行成功」と表示されていました。
このパッチで、失敗がリターンコードで返るようになるため、WUIに「失敗」と表示されるようになります。
本当は「Scheduler is already running.」を画面に表示したかったのですが、apiに手を入れるのにためらわれたため、ここまででPRとします。
同じ構文があと2箇所ありますが、どうしましょうかね？
=> EPG取得中などでスケジューラの実行に失敗したときにWUIで失敗が分かるようにする

app-scheduler.js
#192 と #204 とほぼ同じ（若干異なる）ことを比較的シンプルに，かつ汎用的に実現するパッチです。これまで上手く処理できなかった以下の様なタイトルと話数の処理を改善します。
* 【字】ワンピース（第４５２話）
* 連続テレビ小説　あさが来た（１８）「新選組参上！」【解】【字】【デ】
* 韓国ドラマ・トライアングル「３話」【日本語字幕】
=> Improve regular expressions for titles and episode numbers

app-scheduler.js
手動予約した番組にマッチするルールを作成し、スケジューラを実行すると同じ番組が重複して予約に追加されていました。その結果、
* 同一時間の他の予約が競合でキャンセルされる（手動の場合は予約情報が消える）
* タイミングによってはその番組の予約情報が全部消えていて、録画が実行されない
* （未確認）同一ファイル名で録画しようとするので何か問題が起こりそう
といった問題が起こっていました。
スケジューラで手動予約の情報をコピーするときに、ルールによって予約されているかをチェックしていなかったことが原因なので、チェックロジックを追加しました。
ワンセグフラグは残していますが、スキップフラグについては無視しました。手動予約が入っていればスキップフラグを立てることができないはずなので。
=> 手動予約した番組にマッチするルールを作成すると起こる問題に対応

app-cli.js, app-operator.js, app-scheduler.js, web/chinachu.css, web/class.js, web/page/dashboard/top.js, web/page/program/view.js, web/page/reserves/list.js, web/page/schedule/table.js
#237 の別アプローチです。
data以下のファイルを増やさないように、reserves.jsonの中に競合している番組も残すように変更しました。
思っていたよりも変更点が少なかったのでこちらの方が良いかもしれません。（WUIへの変更は多くなっていますが）
CSSの変更はおおむねスキップしている番組に準ずる見た目にしていますが、クラスを分けてあるので、適宜修正お願いします。
後、迷っているところとして、./chinachu reserves したときの出力でどう見せようかというところ。
・・・スキップしていても表示しないし、このままでも良いですかね？
=> 手動予約した番組が競合していると、手動予約した情報が消えてしまう問題に対応＠reserves.jsonだけでやる版

web/page/channel/watch.js, web/page/program/watch.js
#247 
リバースプロキシのサブディレクトリで運用する場合、watch.jsがAPIにサブディレクトリを渡さないため、再生が機能しませんでした。
サブディレクトリを渡すようにしました。
=> WUI/Client: リバースプロキシ使用時に再生できない問題を修正

app-operator.js
Tweeterの機能追加です。  
文面作成時のタグを追加しました。
- 録画しているチャンネル名(```<channelname>```)
- 日付(```<date>```)
- 開始時刻(```<starttime>```)
- 終了時刻(```<endtime>```)  
録画終了時にツイートができるようにしました
- config.json内のoperTweeterFormat内に```"end" : "string"```と記述
よろしくお願いします。
=> Add tweeter function

app-operator.js, app-scheduler.js
Rivarunにchを渡す際、typeタグにてBS/CSを動的に変更できると
設定が簡潔となりますのでご検討願います。
```json
"tuners": [
{
"name"        : "PT3-S0-BS",
"isScrambling": false,
"types"       : [ "BS","CS" ],
"command"     : "/usr/local/bin/rivarun --mirakurun 127.0.0.1:8888 --b25 --priority 1 --sid <sid> --ch <type>/<channel> - -",
"noEpg"       : false
},
{
"name"        : "PT3-S1-BS",
"isScrambling": false,
"types"       : [ "BS","CS" ],
"command"     : "/usr/local/bin/rivarun --mirakurun 127.0.0.1:8888 --b25 --priority 1 --sid <sid> --ch <type>/<channel> - -",
"noEpg"       : true
},
{
"name"        : "PT3-T0",
"isScrambling": false,
"types"       : [ "GR" ],
"command"     : "/usr/local/bin/rivarun --mirakurun 127.0.0.1:8888 --b25 --priority 1 --sid <sid> --ch <type>/<channel> - -",
"noEpg"       : false
},
{
"name"        : …
```
=> tuners.command の <type> を channel.type に置換

api/script-channel-watch.vm.js
Webストリーム再生が出来ない
原因：PR #275 の対応漏れ
=> ストリーム再生エラー　修正

app-wui.js
`OutgoingMessage`クラスの`headersSent`プロパティは`ServerResponse.prototype.writeHead`メソッドが実行された後は常に`true`を返すようになります。
そのため、現状 (65d18014e67ac7d1e270ea36133bfa5ab84d9ed5) において[app-wui.jsの287行目から360行目](https://github.com/kanreisa/Chinachu/blob/65d18014e67ac7d1e270ea36133bfa5ab84d9ed5/app-wui.js#L287-L360)が呼び出されることはありません。
このPull Requestでは`ServerResponse.prototype.writeHead`メソッドを囲う`if`文のstatement中に、元は別の`if`文に分けられていた処理を入れるよう修正を加え、response bodyへの追加が正常であると思われる形になるようにしています。
こちら意図と違う処理となっていましたらご指摘いただけますとなによりです。
=> WUI: HTTPエラーのreason phraseがresponse bodyに含まれていない不具合を修正

app-scheduler.js
些細なFIXですが、関西地方ＭＢＳ毎日放送のアニメイズム枠EPGタイトルから正しいタイトルを取得する為の修正です。
修正前は以下のようにタイトルが抽出されていました。
完全なタイトル: アニメイズム「迷家ーマヨイガー」　＃０５「ユウナ３人いると紛らわしい」
title: 'アニメイズム', subtitle: '迷家ーマヨイガー'
=> アニメイズム枠タイトル抽出の修正

README.md
Readme.mdのTravis badgeのURLが現在のものと違いましたので、修正しました。
=> Fix: Travis badge URL

api/script-scheduler.vm.js
execSync()内の処理が重くなることがある問題への対処法の一つです。念の為にtacのプロセス優先度もついでに下げてありますが，それでも実用上問題ないことは[下記コメント](https://github.com/kanreisa/Chinachu/compare/devel-beta...tdenc:PR10#commitcomment-13942825)にも書いたとおり確認済みです（さらに良い対処法がありましたら是非コメントください。修正します）。
また，schedulerLogは既にreverseされた文字列が入るので38行目のreverse()は削除し，sedを使うことで最低限の行しか入らないので43〜46行目の処理を削除しました。
=> Speed up api/script-scheduler.vm.js
